FROM ubuntu
ENV DEBIAN_FRONTEND=noninteractive

RUN apt-get update \
    && apt-get install -y wget r-base r-cran-ggplot2 \
    && apt-get clean

RUN Rscript -e 'install.packages(c("ggplot2", "GGally","RColorBrewer","dplyr"))'
