FROM condaforge/miniforge3

RUN conda config --add channels bioconda \
    && conda config --add channels conda-forge \
    && mamba install -y wget git samtools bedtools

RUN pip install pod5

RUN wget https://cdn.oxfordnanoportal.com/software/analysis/dorado-0.8.1-linux-x64.tar.gz
RUN mkdir -p dorado && tar -xzf dorado-0.8.1-linux-x64.tar.gz -C dorado/ --strip-components=1
RUN rm dorado-0.8.1-linux-x64.tar.gz

RUN wget https://github.com/nanoporetech/modkit/releases/download/v0.4.1/modkit_v0.4.1_u16_x86_64.tar.gz
RUN mkdir -p modkit && tar -xzf modkit_v0.4.1_u16_x86_64.tar.gz -C modkit/ --strip-components=1
RUN rm modkit_v0.4.1_u16_x86_64.tar.gz

ENV PATH="$PATH:/modkit:/dorado/bin"

# ONT base calling and methylation processing tools.
# Tools installed: pod5=0.3.15, samtools, bedtools, dorado=0.8.1, modkit=0.4.1