FROM dfam/tetools

RUN apt-get update
RUN apt-get upgrade -y
RUN apt-get install python3-pip git -y

RUN pip install matplotlib pandas pysam tqdm bio more_itertools --break-system-packages

RUN git clone https://github.com/Markloftus/L1ME-AID.git