FROM condaforge/miniforge3
RUN conda config --add channels bioconda \
    && conda config --add channels conda-forge \
    && mamba install -y wget git minimap2 bwa cigar trf

RUN pip install pysam Biopython pandas scipy numpy

RUN git clone https://github.com/REPBIO-LAB/SVAN

WORKDIR /SVAN
