FROM dfam/tetools

RUN apt-get update
RUN apt-get upgrade -y
RUN apt-get install python3-pip git -y

RUN pip install matplotlib pandas pysam tqdm bio more_itertools --break-system-packages

# https://stackoverflow.com/questions/36996046/how-to-prevent-dockerfile-caching-git-clone
# --build-arg CACHEBUST=$(date +%s)
ARG CACHEBUST=1
RUN git clone https://github.com/Markloftus/L1ME-AID.git
ENV PATH="/opt/src/L1ME-AID:${PATH}"